# Generated by Django 5.1.4 on 2025-01-10 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cpf', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cep', models.CharField(max_length=100)),
                ('rua', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('usuario_cpf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localizacoes', to='sistema.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=50)),
                ('mensagem', models.CharField(max_length=500)),
                ('usuario_cpf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='sistema.usuario')),
            ],
        ),
    ]
